version: "3"

services:
  web:
    build: .
    env_file: .env
    restart: always
    volumes:
      - "shared:/tmp"
    command: /app/bin/run-prod.sh

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - "shared:/tmp"
    depends_on:
      - web
    ports:
      - "8000:80"

volumes:
  shared:
